---
language: python
python: "3.6"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install genometools -y
install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
#  - "printf '[defaults]\nroles_path = ../' &gt; ansible.cfg"

script:
  # We'll add some commands to test the role here.
  - ansible-playbook playbook.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
    #  # installing
  - ansible-playbook playbook.yml --tags ami-Setup    
#  - ansible-playbook playbook.yml --tags ami-setup
#  - ansible-playbook playbook.yml --tags amazon-cli
#  - ansible-playbook playbook.yml --tags amazon-cloudwatch
    #  # validating code after installing
#  - ansible-playbook -i tests/inventory tests/test.yml --tags ami-test
  - ansible-playbook -i tests/inventory tests/test.yml --tags ami-setup-validate
  - ansible-playbook -i tests/inventory tests/test.yml --tags amazon-cli-validate
  - ansible-playbook -i tests/inventory tests/test.yml --tags amazon-cloudwatch-validate
