---
    # Install and configure Amazon Cloudwatch Agent
    # -------------------
    - name: Download and place the Cloudwatch Agent Metrics config
      get_url:
        url: https://s3.amazonaws.com/jcrew.shared.software/Amazon/Cloudwatch/AmazonCloudWatch-Linux.json
        dest: /opt/aws/amazon-cloudwatch-agent/etc/AmazonCloudWatch-Linux.json